name: 'Check Version'
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: yarn install
      - uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
