name: 'Check Version'
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: yarn install
      - name: Get version on main branch
        id: mainVersion
        run: git show HEAD~:version
      - name: Output
        run: echo "Version = ${{ steps.mainVersion.outputs }}"
      - uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
